//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMORI_BOT {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OMORI_BOT.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        internal static string ErrorNotFoundSymbol {
            get {
                return ResourceManager.GetString("ErrorNotFoundSymbol", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        internal static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        internal static string SuccessfullyDeletedMessages {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedMessages", resourceCulture);
            }
        }
        
        internal static string ErrorDeletedTwoWeeks {
            get {
                return ResourceManager.GetString("ErrorDeletedTwoWeeks", resourceCulture);
            }
        }
        
        internal static string SuccessfullyDeletedMessagesFromUser {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedMessagesFromUser", resourceCulture);
            }
        }
        
        internal static string SuccessfullyDeletedMessagesWithSymbol {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedMessagesWithSymbol", resourceCulture);
            }
        }
        
        internal static string SuccessfullyRememberBirthday {
            get {
                return ResourceManager.GetString("SuccessfullyRememberBirthday", resourceCulture);
            }
        }
        
        internal static string ErrorRememberBirthday {
            get {
                return ResourceManager.GetString("ErrorRememberBirthday", resourceCulture);
            }
        }
        
        internal static string ErrorDontRemember {
            get {
                return ResourceManager.GetString("ErrorDontRemember", resourceCulture);
            }
        }
        
        internal static string SuccessfullyForgetBirthday {
            get {
                return ResourceManager.GetString("SuccessfullyForgetBirthday", resourceCulture);
            }
        }
        
        internal static string NoMessagesToClear {
            get {
                return ResourceManager.GetString("NoMessagesToClear", resourceCulture);
            }
        }
        
        internal static string NoAccessToUse {
            get {
                return ResourceManager.GetString("NoAccessToUse", resourceCulture);
            }
        }
        
        internal static string SuccessfullyAddToWhiteList {
            get {
                return ResourceManager.GetString("SuccessfullyAddToWhiteList", resourceCulture);
            }
        }
        
        internal static string ErrorDeleteWhiteListServer {
            get {
                return ResourceManager.GetString("ErrorDeleteWhiteListServer", resourceCulture);
            }
        }
        
        internal static string ErrorDeleteWhiteListYet {
            get {
                return ResourceManager.GetString("ErrorDeleteWhiteListYet", resourceCulture);
            }
        }
        
        internal static string SuccesfullyDeleteFromWhiteList {
            get {
                return ResourceManager.GetString("SuccesfullyDeleteFromWhiteList", resourceCulture);
            }
        }
        
        internal static string PrintWhiteList {
            get {
                return ResourceManager.GetString("PrintWhiteList", resourceCulture);
            }
        }
        
        internal static string ErrorPrintWhiteList {
            get {
                return ResourceManager.GetString("ErrorPrintWhiteList", resourceCulture);
            }
        }
        
        internal static string ErrorAddWhiteListServer {
            get {
                return ResourceManager.GetString("ErrorAddWhiteListServer", resourceCulture);
            }
        }
        
        internal static string ErrorAddWhiteListYet {
            get {
                return ResourceManager.GetString("ErrorAddWhiteListYet", resourceCulture);
            }
        }
        
        internal static string ErrorBanAlready {
            get {
                return ResourceManager.GetString("ErrorBanAlready", resourceCulture);
            }
        }
        
        internal static string SuccesfullyBan {
            get {
                return ResourceManager.GetString("SuccesfullyBan", resourceCulture);
            }
        }
        
        internal static string DMBanMessage {
            get {
                return ResourceManager.GetString("DMBanMessage", resourceCulture);
            }
        }
        
        internal static string ErrorUnbanMemberNotBan {
            get {
                return ResourceManager.GetString("ErrorUnbanMemberNotBan", resourceCulture);
            }
        }
        
        internal static string UnBanWithoutReason {
            get {
                return ResourceManager.GetString("UnBanWithoutReason", resourceCulture);
            }
        }
        
        internal static string UnBanWithReason {
            get {
                return ResourceManager.GetString("UnBanWithReason", resourceCulture);
            }
        }
        
        internal static string UnknownDate {
            get {
                return ResourceManager.GetString("UnknownDate", resourceCulture);
            }
        }
        
        internal static string MemberKicked {
            get {
                return ResourceManager.GetString("MemberKicked", resourceCulture);
            }
        }
        
        internal static string DMMessageKick {
            get {
                return ResourceManager.GetString("DMMessageKick", resourceCulture);
            }
        }
        
        internal static string EditLangOnServer {
            get {
                return ResourceManager.GetString("EditLangOnServer", resourceCulture);
            }
        }
        
        internal static string UpcomingBirthdays {
            get {
                return ResourceManager.GetString("UpcomingBirthdays", resourceCulture);
            }
        }
    }
}
